// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vlaakoznrxuopcsobnlv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsYWFrb3pucnh1b3Bjc29ibmx2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNTI1MzYsImV4cCI6MjA1ODgyODUzNn0.LvU-qacNTxbv9eoX6tseMVXkijWpwiplzbdkU06mtxo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);